language: python
python:
  - 3.6
install:
  - pip install sphinx sphinx_rtd_theme sphinx-argparse recommonmark
  - pip install -r requirements.txt

script: cd docs/sources && make html && cd ../..

deploy:
  provider: pages:git
  email: sami@dahoux.net
  local_dir: 'docs/build/all/html'
  keep_history: true
  edge: true
  on:
    branch: master
