language: python
python:
  - 3.6
install:
  - pip install sphinx sphinx_rtd_theme sphinx-argparse recommonmark
  - pip install -r requirements.txt

script: cd docs/sources && make html

deploy:
  email: sami@dahoux.net
  local_dir: 'docs/build/html'
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
