language: python
python:
- 3.6
install:
- pip install sphinx sphinx_rtd_theme sphinx-argparse recommonmark
- pip install -r requirements.txt

scripts:
- echo "Unit testing..."
- python -m unittest tests.test_aes
- python -m unittest tests.test_log
- python -m unittest tests.test_traces
- echo "Generating documentation..."
- cd docs/sources
- make html
- cd ../build/all/html
- touch .nojekyll
- cd ../../../../

before_deploy:
- openssl aes-256-cbc -K $encrypted_b5cde2e0c765_key -iv $encrypted_b5cde2e0c765_iv
  -in deploy_sca.enc -out deploy_sca -d
  
deploy:
  provider: pages:git
  email: sami@dahoux.net
  deploy_key: deploy_sca
  local_dir: docs/build/all/html
  keep_history: true
  edge: true
  on:
    branch: master
